spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lifestats?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: taehyun
    password: 비밀번호입력

mybatis:
  type-aliases-package: com.taehyun.lifestats_backend.domain
  mapper-locations: classpath:/mappers/**/*.xml

server:
  port: 8080